# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runetale < Formula
  desc "P2P mesh network using WireGuard"
  homepage "https://runetale.com/"
  version "0.0.1"
  license "BSD3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runetale/runetale/releases/download/v0.0.1/runetale_0.0.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "43a814b05628e505fd4fee3f92ee49267c203d9e60c53e2afecd90110f907e40"

      def install
        bin.install "runetale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runetale/runetale/releases/download/v0.0.1/runetale_0.0.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0c58e4146b2029b9bf6d433c061c98a7f88026dd9b65bbd7e068beb6f627bd60"

      def install
        bin.install "runetale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runetale/runetale/releases/download/v0.0.1/runetale_0.0.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "876dd2ed033351b16aad385070f7f08905154c989db2909db973075c11045d52"

      def install
        bin.install "runetale"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/runetale/runetale/releases/download/v0.0.1/runetale_0.0.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "beac6f911c67bd4cc28beec9ebae084b03da692bfc96a64e8f5c2bc557901fb5"

      def install
        bin.install "runetale"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/runetale/runetale/releases/download/v0.0.1/runetale_0.0.1_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "4c369f881515ad074d347d00635b6191848c81def4b45d6b52a3d4867675626b"

      def install
        bin.install "runetale"
      end
    end
  end

  test do
    system "#{bin}/runetale version"
  end
end
