# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runetaled < Formula
  desc "p2p mesh network"
  homepage "https://runetale.com/"
  version "0.0.8"
  license "BSD3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/runetale/runetale/releases/download/v0.0.8/runetaled_0.0.8_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "29ca2c07ed4f6fc3288fdb1959a5f0af8b68b1954dfd7a3c19df76b3f7ee6fdb"

      def install
        bin.install "runetaled"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/runetale/runetale/releases/download/v0.0.8/runetaled_0.0.8_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "d0194694e79b55d4971b75570c3c93478ced819dc11222179ec0524efe3b3833"

      def install
        bin.install "runetaled"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/runetale/runetale/releases/download/v0.0.8/runetaled_0.0.8_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "43824146499c4f8ab6dc4d9c94add3d0d6df71c160de4c478d180ec52290eccf"

      def install
        bin.install "runetaled"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/runetale/runetale/releases/download/v0.0.8/runetaled_0.0.8_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "77693953fd75a7474d4850947ddaf5c323c18666245e4da8dd34acbf93a2b6f2"

      def install
        bin.install "runetaled"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runetale/runetale/releases/download/v0.0.8/runetaled_0.0.8_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d7f9dfccaa35fd9dc9960d2f1b3492b9805598418570c662d2bbcbe6dcb05e28"

      def install
        bin.install "runetaled"
      end
    end
  end

  test do
    system "#{bin}/runetaled version"
  end
end
