# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runetale < Formula
  desc "P2P mesh network using WireGuard"
  homepage "https://runetale.com/"
  version "0.0.14-hennge-dev"
  license "BSD3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/runetale/runetale/releases/download/v0.0.14-hennge-dev/runetale_0.0.14-hennge-dev_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0fa22e34c1356d6768b18169f620573297d53bfe26195854c4f73043e1d41c3b"

      def install
        bin.install "runetale"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/runetale/runetale/releases/download/v0.0.14-hennge-dev/runetale_0.0.14-hennge-dev_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "3e047c6a2092d3b2cc17182ba4b59437857da1273ff2ea6643d8d97bd2aae4ad"

      def install
        bin.install "runetale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/runetale/runetale/releases/download/v0.0.14-hennge-dev/runetale_0.0.14-hennge-dev_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "85840b6f24cd06d0ed354f0bd90eea478efb0f0e95b3f41033786142dcad3add"

      def install
        bin.install "runetale"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/runetale/runetale/releases/download/v0.0.14-hennge-dev/runetale_0.0.14-hennge-dev_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "5f0c57fc9b740de6410bd5f91a8d887834887ca0b7918c60bba2d5133b4d6128"

      def install
        bin.install "runetale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runetale/runetale/releases/download/v0.0.14-hennge-dev/runetale_0.0.14-hennge-dev_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "256aacaab42afe9280552a76c978e50ffb905ac37eb4959b8d891b73901b6fd7"

      def install
        bin.install "runetale"
      end
    end
  end

  test do
    system "#{bin}/runetale version"
  end
end
