# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runetale < Formula
  desc "P2P mesh network using WireGuard"
  homepage "https://runetale.com/"
  version "0.0.15-hennge-dev"
  license "BSD3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/runetale/runetale/releases/download/v0.0.15-hennge-dev/runetale_0.0.15-hennge-dev_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "90e789ac859c94d8a4cd995afafd308c34a6833188dbd0d4b7f4b34516c66b34"

      def install
        bin.install "runetale"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/runetale/runetale/releases/download/v0.0.15-hennge-dev/runetale_0.0.15-hennge-dev_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "263efe6790bcb996c9077a458630198ed4f5fdedb14c7b63f8b385ac2b1ccc34"

      def install
        bin.install "runetale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/runetale/runetale/releases/download/v0.0.15-hennge-dev/runetale_0.0.15-hennge-dev_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "85fed0ae235b67d9d06987032dabe76b744df96b9faef4524a5007f22709b99f"

      def install
        bin.install "runetale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runetale/runetale/releases/download/v0.0.15-hennge-dev/runetale_0.0.15-hennge-dev_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "35fcade97007876e00a035bba18f277e4890360cf73758ef1accfd8130160385"

      def install
        bin.install "runetale"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/runetale/runetale/releases/download/v0.0.15-hennge-dev/runetale_0.0.15-hennge-dev_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "78e8975b5474f85d1aa376c8e019c530ed8f3fc47b2ad300384b873477126d43"

      def install
        bin.install "runetale"
      end
    end
  end

  test do
    system "#{bin}/runetale version"
  end
end
