# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runetaled < Formula
  desc "p2p mesh network"
  homepage "https://runetale.com/"
  version "0.0.15"
  license "BSD3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/runetale/runetale/releases/download/v0.0.15/runetaled_0.0.15_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c328279ce981dc2dd9c17f4cb35941a3e144a7c1bf09e62df8ad4205e28718eb"

      def install
        bin.install "runetaled"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/runetale/runetale/releases/download/v0.0.15/runetaled_0.0.15_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "d1338075a0d4efdc398d95af08ef9f55315c1cb80b4d5f1c8af5962250465c0c"

      def install
        bin.install "runetaled"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/runetale/runetale/releases/download/v0.0.15/runetaled_0.0.15_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "702ad58d3304cf574b2904a1a494455d4751460ca71f83a49591166ecaa12422"

      def install
        bin.install "runetaled"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runetale/runetale/releases/download/v0.0.15/runetaled_0.0.15_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "a0295eb6078e41e7f94650ba0142970ce762efccf3a09016ce111213d911eca3"

      def install
        bin.install "runetaled"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/runetale/runetale/releases/download/v0.0.15/runetaled_0.0.15_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e6220b534209199d284195bb87d7b946ff44b2de1fa360c77da23d4d469c8698"

      def install
        bin.install "runetaled"
      end
    end
  end

  test do
    system "#{bin}/runetaled version"
  end
end
