# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runetaled < Formula
  desc "p2p mesh network"
  homepage "https://runetale.com/"
  version "0.0.14-hennge-dev"
  license "BSD3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runetale/runetale/releases/download/v0.0.14-hennge-dev/runetaled_0.0.14-hennge-dev_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "910553235beebe01915cb80c8c85074c5d180ae1416c38daf875e574a39feadc"

      def install
        bin.install "runetaled"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runetale/runetale/releases/download/v0.0.14-hennge-dev/runetaled_0.0.14-hennge-dev_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6f9315d0351d88ebb3698b86787e854f7797a8575cee5512cac2984100124c30"

      def install
        bin.install "runetaled"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/runetale/runetale/releases/download/v0.0.14-hennge-dev/runetaled_0.0.14-hennge-dev_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "cb9268db0fef3e2fac7ae95fbefe9ccbdd3c6894cddb46bc086fe876e274c367"

      def install
        bin.install "runetaled"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/runetale/runetale/releases/download/v0.0.14-hennge-dev/runetaled_0.0.14-hennge-dev_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "2c1928075cb60bf0ebc5c3c185bb1e9a969e891dbf6fbc9d7abd345b30cadca3"

      def install
        bin.install "runetaled"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runetale/runetale/releases/download/v0.0.14-hennge-dev/runetaled_0.0.14-hennge-dev_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "010a6d02cb8965a8a64fe2dd89ded1ca4e67bf0918c49c5d09cdf53c29f8bbe5"

      def install
        bin.install "runetaled"
      end
    end
  end

  test do
    system "#{bin}/runetaled version"
  end
end
